import React from 'react'
export const Info = [
  
{image: 'https://images.unsplash.com/photo-1591797159149-27d30c0a99f8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
title:'Human Resources Specialist (42A)',
text:"As a military veteran I served over 4 years as a human resources specialist. Some of my daily deliverables consisted of managing service member relations, payroll and benefits, assisting in Army Career development to include future training, academy selection, providing personnel support and assistance in regards to DFAS (Defense Finance and Accounting Services). As I climbed the ranks to a Human Resources Lead I managed a team of 6 service members and my responsibilities expanded to establish process improvements, streamline procedures to effectively report on accountability, budget allocation, safety and risk assessments & develop intra-office communication protocols. I also streamlined administrative procedures, and  helped with the unit's inventory control.  "},
{image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=824&q=80',
title:'Mortgage Banker',
text: "After my military service I quickly transitioned into sales. Why sales, because finding value and communicating effectively with people wasn't my strong suit especially after spending years in the military. After my Buisness Development internship with Vista Vending I quickly joined a small bank where I learned how to sell, build a book of business and network within the community. Some of my daily deliverables consisted of evaluating P&Ls along with numerous financial statements for accurate security assessment, Meet production goals by engaging in client management CRM software. Pre-screening and pre- qualifying client base through extensive co-marketing alongside realtors and account executives. Outline financing proposals for first time home buyers and help investors assess cash flow portfolio management. Structure FHA, VA, USDA, and Conventional (FNMA & FHLMC) financing acquisition and refinance loan products.  "},
{image: 'https://images.unsplash.com/photo-1503387837-b154d5074bd2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=889&q=80',
title:'Business Development Manager ',
text: " Once I departed from Mortgage Solutions I took my knowledge and expertise to a construction company in need of expanding it's business across the pacific north west. Some of my daily deliverables consisted of oversee marketing functions to identify key marketing strategies, further expanding acquisition and sale opportunities. Interview, onboard, and train sales professionals. Coaching and motivating to reach quarterly and annual goals. Work closely with VP, GM, and Regional Director to develop customer acquisition strategies to obtain maximum sale volume.  "},
{image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80',
title:'Human Resources Coordinator ',
text: " At Moe's Home Collection I had the opportunity to develop relationships with all levels of the company from C-suite executives to the warehouse workers I helped manage. Some of my daily deliverables consisted of outline financial propositions' to contend with market salary rates. Establish process improvements and streamline procedures to effectively report on accountability, budget allocation, safety and risk assessments. Screening, Interviewing, and onboarding candidates. Manage employee relations, payroll and benefits. Cross departmental collaboration on education, safety committees and skill programs for professional development.  "},



  
]